<a href="https://colab.research.google.com/github/HuZichun1/Github/blob/main/HW_0_STA208_S24_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **HW#0-STA208-S24: Getting Started / Warmup Exercises**

## Part I: (Do not turn in)

Basics of how to work with jupyter notebooks and colab.

**Colab/notebooks:**

- colab and google drive
- code cells / text cells
- save (and pin) notebooks
- markdown
- latex

- I/O (see below; reference: https://colab.research.google.com/notebooks/io.ipynb)

**Resources:**

[Very basics of LATEX](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Overview of Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)

[Guide to Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)

[Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)



### I/O on Colab and using bash commands (this section is also in the notebook "lecture1")

To upload a file to Colab from a local drive, run the following code (you will be prompted to select the file);

In [ ]:
from google.colab import files
uploaded = files.upload()

# the below shows that I have imported the file "winequality-red.csv" (to do this click
# on the prompt "Choose Files" and select from your local machine)

- Alternatively, you can also mount your entire google drive, and then have access to all the files there; after mounting google drive there is no need to individually upload files;
- To mount google drive, you can either click on the corresponding "mount" icon in the left column under 'Files', or run the next code cell, or use below code;
- then run the subsequent code cell to load the `winequality' data


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
## Lines that start with ! run a bash (shell) command

# If mounting google drive, run the following to see whether the winedata file is accessible
# !ls -l /content/drive/MyDrive/data/winequality-red.csv

# if uploading the data from a local drive, run the following to see whether the winedata file is accessible
!ls -l winequality-red.csv

-rw-r--r-- 1 root root 84199 Apr  1 16:26 winequality-red.csv


In [ ]:
# If google drive has been mounted, run the following to see the header of the file
# !head /content/drive/MyDrive/data/winequality-red.csv

# If data file has been loaded from a local drive, run the following to see the header of the file
!head winequality-red.csv

"fixed acidity";"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5
7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;9.8;5
11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58;9.8;6
7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
7.4;0.66;0;1.8;0.075;13;40;0.9978;3.51;0.56;9.4;5
7.9;0.6;0.06;1.6;0.069;15;59;0.9964;3.3;0.46;9.4;5
7.3;0.65;0;1.2;0.065;15;21;0.9946;3.39;0.47;10;7
7.8;0.58;0.02;2;0.073;9;18;0.9968;3.36;0.57;9.5;7



### Review basics of python, numpy, pandas
(official Python documentation: https://docs.python.org/3/)

- lists, tuples, arrays (perhaps dictionaries, sets)
- functions
- if else; for loops
- [f(a) for a in L] list comprehension (e.g. see https://www.pythoncheatsheet.org/cheatsheet/comprehensions)
- copying vs. referencing
- mutable - immutable (e.g. see https://realpython.com/python-mutable-vs-immutable-types/)

<br>

- slicing a numpy array
- pandas dataframes (e.g. see https://pandas.pydata.org/docs/reference/frame.html)
- slicing a pandas dataframe
- subsetting using iloc and loc
- subsetting using criteria
- fit(), predict(), transform() (fit_predict(), fit_transfrom()) methods

**General resources:**
- https://www.pythoncheatsheet.org/
- https://pandas.pydata.org/docs/reference/io.html



### Part II: Some Exercises (turn in for credit)

These exercises are meant to recall basic geometric interpretation underlying concepts from linear algebra and to get some practice in using basic numpy/python.


1) Add a new text cell to this notebook right below the fomulation of this problem 1 (in particular, split the cell - see keyboard shortcuts in the tools dropdown menu for the command) and add your answers to this problem there. Use LATEX for writing formulas.

Suppose $u$ is a $d$-dimensional vector that is normal to a hyperplane $H$. Consider the $(d \times d)$-matrix

$$U := I_d - \frac{1}{\|u\|^2}uu^\top.$$

a) Show that for any $d$-dimensional vector $v$, the vector $Uv$ (matrix multiplication) lies in $H$. [HINT: Show this by using the property of a normal vector.]

b) Provide a geometric interpretation of the vector $Uv$ (i.e. describe how it relates geometrically to $v$).

c) With $I_d$ denoting the $(d \times d)$_identity matrix, the matrix

$$U^* := I_d - \frac{2}{\|u\|^2}uu^\top$$

is called *elementary reflector* (or sometimes *Hausholder transformation*). Compare the vector $U^*v$ to $Uv$ and explain the name *elementary reflector*. [HINT: Drawing a figure for $d=2$ might help.]



$\text{(a)}$
If vector $Uv$ lies in H, then it should be orthogonal with u.
$$
u'( I_d-\frac{uu'}{\|u\|^2})v
$$
$$
=(u' \cdot v) - \frac{(u' \cdot u)}{\|u\|^2}(u' \cdot v) = 0
$$
Therefore, vector $Uv$ lies in H.

(b)
$Uv$ represents the smallest distance between v and the projection of v onto u

(c)
Take the vector symmetric with respect to the plane and get a new vector. And That's the reason why the name of the vector is reflector.

2) Use numpy to do the computations in this problem. To this end, use this notebook, add a code cell right below the formulation of this problem and put your solutions there.

a) Define $u = (1,2,3,3,2,1)$, $v = (1,2,3,4,5,6).$
- Compute the matrix $U = I - \frac{1}{\|u\|^2}uu^\top$ and find $Uv$ (print both, the matrix $U$ and the vector $Uv$)
- Compute $U^* = I - \frac{2}{\|u\|^2}uu^\top$ and find $U^*v$ (print both, the matrix $U^*$ and the vector $U^*v$).

b)  Consider the real value
$\alpha = \frac{\langle u, Uv-U^*v\rangle}{\|u\|\cdot\|Uv - U^*v\|}.$
- Make a conjecture of what the value of $\alpha$ is (use your geometric intuition - again, drawing a figure in $d=2$ should help).
- Compute $\alpha$, and explain the value you obtain.


In [2]:
import numpy as np
#a
u=np.array([1, 2, 3, 3, 2, 1])
v=np.array([1, 2, 3, 4, 5, 6])

ulength=np.linalg.norm(u)

U=np.eye(6)-(1/ulength)**2 * np.outer(u,u)

print("U:",U)
print("Uv:",U@v)

Ustar=np.eye(6)-2*(1/ulength)**2 * np.outer(u,u)

print("U*:",Ustar)
print("U*v:",Ustar@(v))

#b My conjecture here is that the alpha is equal to cos(0) which is 1.

alpha=np.inner(u,U@(v)-Ustar@(v))/(np.linalg.norm(u)*np.linalg.norm(U@(v)-Ustar@(v)))
print("alpha",alpha,"which is really closed to 1, since the alpha represents cosine value of the angle between the vector u and Uv-U*v.")



U: [[ 0.96428571 -0.07142857 -0.10714286 -0.10714286 -0.07142857 -0.03571429]
 [-0.07142857  0.85714286 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.10714286 -0.21428571  0.67857143 -0.32142857 -0.21428571 -0.10714286]
 [-0.10714286 -0.21428571 -0.32142857  0.67857143 -0.21428571 -0.10714286]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571  0.85714286 -0.07142857]
 [-0.03571429 -0.07142857 -0.10714286 -0.10714286 -0.07142857  0.96428571]]
Uv: [-0.5 -1.  -1.5 -0.5  2.   4.5]
U*: [[ 0.92857143 -0.14285714 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.14285714  0.71428571 -0.42857143 -0.42857143 -0.28571429 -0.14285714]
 [-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]
 [-0.21428571 -0.42857143 -0.64285714  0.35714286 -0.42857143 -0.21428571]
 [-0.14285714 -0.28571429 -0.42857143 -0.42857143  0.71428571 -0.14285714]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571 -0.14285714  0.92857143]]
U*v: [-2. -4. -6. -5. -1.  3.]
alpha 0.9999999999999998

3) Consider the matrix $UU^\top$ with $U$ from above. We are now concerned about the eigenvalues of $UU^\top$.

- Make a conjecture about the values of the eigenvalues of $UU^\top$ (positive, negative, zero, certain specific values??).

- Compute the eigenvalues using numpy and iterprete the values that you find.

- Explain why $UU^\top = UU = U$, i.e. $U$ is idempotent.

- Let $V$ be the $(6 \times 3)$-matrix consisting of the first three columns of $U$. Is $V$ also idempotent? Explain.

In [ ]:
# My conjecture here is the eigenvalue of the UU' are all 0 and 1

UU= U@U
eigenvalues, eigenvectors = np.linalg.eig(UU)

print("eigenvalues",eigenvalues)
# The second eigenvalue here is approximately 0, which means that the matrix is approximately singular.

# Since U is a projection matrix, so it is idempotent

# VV' is a 6*6 matrix, but V is a 6*3 matrix. Therefore, it is not idempotent.


eigenvalues [ 1.00000000e+00 -4.16333634e-17  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00]


4) Some numpy practice: With $U = (U_{ij})_{i,j=1,\ldots,6}$ from above do the following:

- Find the largest and smallest off-diagonal elements of $UU^\top$.

- Find the largest and smallest diagonal elements of $UU^\top$.

- Compute the value $max_i \sum_{j} |U_{ij}|$.

- Print the elements of the second column of $UU^\top$ below the diagonal.

- Verify idempotence of $U$ by showing that $UU - U = 0$ (where the $0$ on the right hand side is the $0$-matrix).




In [ ]:
#1
off_diagonal_elements = UU[~np.eye(UU.shape[0],dtype=bool)]
print("max off-diagonal", np.max(off_diagonal_elements))
print("min off-diagonal", np.min(off_diagonal_elements))

#2
diagonal_elements = UU[np.eye(UU.shape[0],dtype=bool)]
print("max diagonal", np.max(diagonal_elements))
print("min diagonal", np.min(diagonal_elements))

#3
print("maxi",np.max(np.sum(np.abs(U), axis=1)))

#4
print(UU[2:, 1])

#5
check = np.allclose(UU - U, 0, atol=1e-8)
print(check)

max off-diagonal -0.03571428571428571
min off-diagonal -0.3214285714285714
max diagonal 0.9642857142857143
min diagonal 0.6785714285714285
maxi 1.6428571428571428
[-0.21428571 -0.21428571 -0.14285714 -0.07142857]
True
